version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      TZ: Asia/Singapore
    volumes:
     - mongo_data:/data/db

  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - TZ=Asia/Singapore

  frontend:
    build:
      context: ./Frontend/pyjobs_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  mongo_data: {}
